services:
  sclipi-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: sclipi-server
    network_mode: "host"
    environment:
      SCLIPI_SERVERPORT: 8080
      SCLIPI_DEFAULTSCPISOCKETPORT: 5025
      SCLIPI_DEFAULTSCPISOCKETADDRESS: "localhost"
      SCLIPI_CONNECTIONMODE: "per-client"
      SCLIPI_PREFERENCESFILEPATH: "/app/data/preferences.json"
    volumes:
      - sclipi-data:/app/data
    restart: unless-stopped

volumes:
  sclipi-data:
