services:
  scpir-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/bhutch29/scpir:master
    network_mode: "host"
    environment:
      SCPIR_SERVERPORT: 8080
      SCPIR_DEFAULTSCPISOCKETPORT: 5025
      SCPIR_DEFAULTSCPISOCKETADDRESS: "localhost"
      SCPIR_CONNECTIONMODE: "per-client"
      SCPIR_PREFERENCESFILEPATH: "/app/data/preferences.json"
    volumes:
      - scpir-data:/app/data
    restart: unless-stopped

volumes:
  scpir-data:
