name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build CLI
      run: go build -v ./cmd/cli

    - name: Test
      run: go test -v
